name:                webserver
version:             0.1.0.0
license:             BSD3

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/yesod-sqlite#readme>

dependencies:
  - base >= 4.7 && < 5
  - yesod
  - containers
  - stm

library:
  source-dirs: src
  exposed-modules:
    - Dispatch
    - Foundation
  dependencies:
    - data-default
    - text
    - bytestring
    - conduit
    - conduit-extra
    - resourcet
    - blaze-markup
    - shakespeare
    - cassava
    - vector
    - http-types
    - yesod-form
    - yesod-persistent
    - yesod-core
    - time
    - transformers

executables:
  webserver:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - webserver

tests:
  webserver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - webserver
